database:
  default: postgresql  
  mysql:
    url: jdbc:mysql://localhost:3306/dette_gestionJdbc 
    username: root
    password: ""
    driver: com.mysql.cj.jdbc.Driver
  postgresql:
    url: jdbc:postgresql://localhost:5432/dette_gestionJdbc
    username: postgres
    password: "passer"
    driver: org.postgresql.Driver

persistence:
  repository:
    type: bd  


